version: '0.1.{build}'
configuration: Release
image: Visual Studio 2017

max_jobs: 1
skip_non_tags: true
clone_depth: 1

branches:
  only:
    - master

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

install:
- ps: dotnet restore -s "https://api.nuget.org/v3/index.json" --verbosity m

after_build:
- ps: ./Build.ps1

artifacts:
 - path: '**\*.nupkg'

deploy:
  - provider: NuGet
    api_key:
      secure: qv8neZddxXHFevH4lLUAfjVud3fhjTR3J022rlTsgIPqkASxZ/jHjB38nkUJYFGT
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      branch: master

  - provider: GitHub
    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    auth_token:
      secure: ciT780F14J207Y8r947Il6TBZQG8xJfvYqOZaU+EsBhDzzzN/sdtETKju59U6hbs
    on:
      branch: master                # release from master branch only