//------------------------------------------------------------------------------
// <auto-generated>
//		This code was generated from a template.
//		Manual changes to this file may cause unexpected behavior in your application.
//		Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Net.Http;
using Flurl.Http;
using Flurl;
using System.Runtime.CompilerServices;
using AspNetCore.Client.Core;
using AspNetCore.Client.Core.Authorization;
using AspNetCore.Client.Core.Exceptions;
using Microsoft.Extensions.DependencyInjection;
using System.Threading;
using Newtonsoft.Json;

namespace TestWebApp.Clients
{


	public static class TestWebAppClientInstaller
	{
		/// <summary>
		/// Register the autogenerated clients into the container with a lifecycle of scoped.
		/// </summary>
		/// <param name="services"></param>
		/// <param name="baseAddress">Address to be used inside the HttpClient injected</param>
		/// <returns></returns>
		public static IServiceCollection InstallClients(this IServiceCollection services, string baseAddress = null)
		{
			services.AddScoped<TestWebAppClient>((provider) =>
			{
				var client = provider.GetService<HttpClient>();
				if(baseAddress != null)
				{
					client.BaseAddress = new Uri(baseAddress);
				}
				return new TestWebAppClient(client);
			});

			services.AddScoped<IValuesClient, ValuesClient>();
			return services;
		}
	}


	public interface IHttpOverride
	{
		ValueTask<HttpResponseMessage> GetResponseAsync(String url, CancellationToken cancellationToken = default(CancellationToken));
		Task OnNonOverridedResponseAsync(String url, HttpResponseMessage response, CancellationToken cancellationToken = default(CancellationToken));
	}



	public class TestWebAppClient
	{
		public readonly FlurlClient ClientWrapper;

		public TestWebAppClient(HttpClient client)
		{
			ClientWrapper = new FlurlClient(client);
		}
	}

	public interface ITestWebAppClient : IClient { }



	public interface IValuesClient : ITestWebAppClient
	{
		
		IEnumerable<string> Get(int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		HttpResponseMessage GetRaw(int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		ValueTask<IEnumerable<string>> GetAsync(int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		ValueTask<HttpResponseMessage> GetRawAsync(int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		string Get(int id, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		HttpResponseMessage GetRaw(int id, 
			int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		ValueTask<string> GetAsync(int id, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		ValueTask<HttpResponseMessage> GetRawAsync(int id, 
			int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		void Post(string value, 
			int UserId, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		HttpResponseMessage PostRaw(string value, 
			int UserId, 
			int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		Task PostAsync(string value, 
			int UserId, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		ValueTask<HttpResponseMessage> PostRawAsync(string value, 
			int UserId, 
			int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		void Put(int id, 
			string value, 
			int UserId, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		HttpResponseMessage PutRaw(int id, 
			string value, 
			int UserId, 
			int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		Task PutAsync(int id, 
			string value, 
			int UserId, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		ValueTask<HttpResponseMessage> PutRawAsync(int id, 
			string value, 
			int UserId, 
			int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		void Delete(int id, 
			int UserId, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			SecurityHeader auth = null, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		HttpResponseMessage DeleteRaw(int id, 
			int UserId, 
			int ControllerHeader = 0, 
			SecurityHeader auth = null, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		Task DeleteAsync(int id, 
			int UserId, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			SecurityHeader auth = null, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		ValueTask<HttpResponseMessage> DeleteRawAsync(int id, 
			int UserId, 
			int ControllerHeader = 0, 
			SecurityHeader auth = null, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		void CancellationTestEndpoint(int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		HttpResponseMessage CancellationTestEndpointRaw(int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		Task CancellationTestEndpointAsync(int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		ValueTask<HttpResponseMessage> CancellationTestEndpointRawAsync(int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		string HeaderTest(String SpecialValue1, 
			string SpecialValue2, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		HttpResponseMessage HeaderTestRaw(String SpecialValue1, 
			string SpecialValue2, 
			int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		ValueTask<string> HeaderTestAsync(String SpecialValue1, 
			string SpecialValue2, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken));

		
		ValueTask<HttpResponseMessage> HeaderTestRawAsync(String SpecialValue1, 
			string SpecialValue2, 
			int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken));

	}


	public class ValuesClient : IValuesClient
	{
		public readonly TestWebAppClient Client;
		public readonly IHttpOverride HttpOverride;

		public ValuesClient(TestWebAppClient client, IHttpOverride httpOverride)
		{
			Client = client;
			HttpOverride = httpOverride;
		}


		public IEnumerable<string> Get(int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}";
			HttpResponseMessage response = null;
			response = HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			if(response == null)
			{
				response = Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.GetAsync(cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
				
				HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			}

			if(BadRequestCallback != null && BadRequestCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for BadRequestCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.BadRequest)
			{
				BadRequestCallback?.Invoke(response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false).GetAwaiter().GetResult());
			}
			if(InternalServerErrorCallback != null && InternalServerErrorCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for InternalServerErrorCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
			{
				InternalServerErrorCallback?.Invoke();
			}
			if(ResponseCallback != null && ResponseCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for ResponseCallback are not supported. As they will run out of the scope of this call.");
			}
			ResponseCallback?.Invoke(response);
			
			if(response.IsSuccessStatusCode)
			{
				return JsonConvert.DeserializeObject<IEnumerable<string>>(response.Content.ReadAsStringAsync().ConfigureAwait(false).GetAwaiter().GetResult());
			}
			else
			{
				return null;
			}

		}


		public HttpResponseMessage GetRaw(int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}";
			HttpResponseMessage response = null;
			response = HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			if(response == null)
			{
				response = Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.GetAsync(cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
				
				HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			}

			return response;
		}


		public async ValueTask<IEnumerable<string>> GetAsync(int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}";
			HttpResponseMessage response = null;
			response = await HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false);
			if(response == null)
			{
				response = await Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.GetAsync(cancellationToken).ConfigureAwait(false);
				
				await HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false);
			}

			if(BadRequestCallback != null && BadRequestCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for BadRequestCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.BadRequest)
			{
				BadRequestCallback?.Invoke(await response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false));
			}
			if(InternalServerErrorCallback != null && InternalServerErrorCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for InternalServerErrorCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
			{
				InternalServerErrorCallback?.Invoke();
			}
			if(ResponseCallback != null && ResponseCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for ResponseCallback are not supported. As they will run out of the scope of this call.");
			}
			ResponseCallback?.Invoke(response);
			
			if(response.IsSuccessStatusCode)
			{
				return JsonConvert.DeserializeObject<IEnumerable<string>>(await response.Content.ReadAsStringAsync().ConfigureAwait(false));
			}
			else
			{
				return null;
			}

		}


		public async ValueTask<HttpResponseMessage> GetRawAsync(int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}";
			HttpResponseMessage response = null;
			response = await HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false);
			if(response == null)
			{
				response = await Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.GetAsync(cancellationToken).ConfigureAwait(false);
				
				await HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false);
			}

			return response;
		}


		public string Get(int id, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}/{id}";
			HttpResponseMessage response = null;
			response = HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			if(response == null)
			{
				response = Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.GetAsync(cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
				
				HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			}

			if(BadRequestCallback != null && BadRequestCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for BadRequestCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.BadRequest)
			{
				BadRequestCallback?.Invoke(response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false).GetAwaiter().GetResult());
			}
			if(InternalServerErrorCallback != null && InternalServerErrorCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for InternalServerErrorCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
			{
				InternalServerErrorCallback?.Invoke();
			}
			if(ResponseCallback != null && ResponseCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for ResponseCallback are not supported. As they will run out of the scope of this call.");
			}
			ResponseCallback?.Invoke(response);
			
			if(response.IsSuccessStatusCode)
			{
				return response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false).GetAwaiter().GetResult();
			}
			else
			{
				return null;
			}

		}


		public HttpResponseMessage GetRaw(int id, 
			int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}/{id}";
			HttpResponseMessage response = null;
			response = HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			if(response == null)
			{
				response = Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.GetAsync(cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
				
				HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			}

			return response;
		}


		public async ValueTask<string> GetAsync(int id, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}/{id}";
			HttpResponseMessage response = null;
			response = await HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false);
			if(response == null)
			{
				response = await Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.GetAsync(cancellationToken).ConfigureAwait(false);
				
				await HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false);
			}

			if(BadRequestCallback != null && BadRequestCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for BadRequestCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.BadRequest)
			{
				BadRequestCallback?.Invoke(await response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false));
			}
			if(InternalServerErrorCallback != null && InternalServerErrorCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for InternalServerErrorCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
			{
				InternalServerErrorCallback?.Invoke();
			}
			if(ResponseCallback != null && ResponseCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for ResponseCallback are not supported. As they will run out of the scope of this call.");
			}
			ResponseCallback?.Invoke(response);
			
			if(response.IsSuccessStatusCode)
			{
				return await response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false);
			}
			else
			{
				return null;
			}

		}


		public async ValueTask<HttpResponseMessage> GetRawAsync(int id, 
			int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}/{id}";
			HttpResponseMessage response = null;
			response = await HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false);
			if(response == null)
			{
				response = await Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.GetAsync(cancellationToken).ConfigureAwait(false);
				
				await HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false);
			}

			return response;
		}


		public void Post(string value, 
			int UserId, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}?value={value}";
			HttpResponseMessage response = null;
			response = HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			if(response == null)
			{
				response = Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("UserId", UserId)
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.PutJsonAsync(value,cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
				
				HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			}

			if(BadRequestCallback != null && BadRequestCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for BadRequestCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.BadRequest)
			{
				BadRequestCallback?.Invoke(response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false).GetAwaiter().GetResult());
			}
			if(InternalServerErrorCallback != null && InternalServerErrorCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for InternalServerErrorCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
			{
				InternalServerErrorCallback?.Invoke();
			}
			if(ResponseCallback != null && ResponseCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for ResponseCallback are not supported. As they will run out of the scope of this call.");
			}
			ResponseCallback?.Invoke(response);
			return;
		}


		public HttpResponseMessage PostRaw(string value, 
			int UserId, 
			int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}?value={value}";
			HttpResponseMessage response = null;
			response = HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			if(response == null)
			{
				response = Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("UserId", UserId)
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.PutJsonAsync(value,cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
				
				HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			}

			return response;
		}


		public async Task PostAsync(string value, 
			int UserId, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}?value={value}";
			HttpResponseMessage response = null;
			response = await HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false);
			if(response == null)
			{
				response = await Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("UserId", UserId)
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.PutJsonAsync(value,cancellationToken).ConfigureAwait(false);
				
				await HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false);
			}

			if(BadRequestCallback != null && BadRequestCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for BadRequestCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.BadRequest)
			{
				BadRequestCallback?.Invoke(await response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false));
			}
			if(InternalServerErrorCallback != null && InternalServerErrorCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for InternalServerErrorCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
			{
				InternalServerErrorCallback?.Invoke();
			}
			if(ResponseCallback != null && ResponseCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for ResponseCallback are not supported. As they will run out of the scope of this call.");
			}
			ResponseCallback?.Invoke(response);
			return;
		}


		public async ValueTask<HttpResponseMessage> PostRawAsync(string value, 
			int UserId, 
			int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}?value={value}";
			HttpResponseMessage response = null;
			response = await HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false);
			if(response == null)
			{
				response = await Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("UserId", UserId)
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.PutJsonAsync(value,cancellationToken).ConfigureAwait(false);
				
				await HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false);
			}

			return response;
		}


		public void Put(int id, 
			string value, 
			int UserId, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}/{id}?value={value}";
			HttpResponseMessage response = null;
			response = HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			if(response == null)
			{
				response = Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("UserId", UserId)
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.PutJsonAsync(value,cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
				
				HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			}

			if(BadRequestCallback != null && BadRequestCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for BadRequestCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.BadRequest)
			{
				BadRequestCallback?.Invoke(response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false).GetAwaiter().GetResult());
			}
			if(InternalServerErrorCallback != null && InternalServerErrorCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for InternalServerErrorCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
			{
				InternalServerErrorCallback?.Invoke();
			}
			if(ResponseCallback != null && ResponseCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for ResponseCallback are not supported. As they will run out of the scope of this call.");
			}
			ResponseCallback?.Invoke(response);
			return;
		}


		public HttpResponseMessage PutRaw(int id, 
			string value, 
			int UserId, 
			int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}/{id}?value={value}";
			HttpResponseMessage response = null;
			response = HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			if(response == null)
			{
				response = Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("UserId", UserId)
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.PutJsonAsync(value,cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
				
				HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			}

			return response;
		}


		public async Task PutAsync(int id, 
			string value, 
			int UserId, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}/{id}?value={value}";
			HttpResponseMessage response = null;
			response = await HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false);
			if(response == null)
			{
				response = await Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("UserId", UserId)
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.PutJsonAsync(value,cancellationToken).ConfigureAwait(false);
				
				await HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false);
			}

			if(BadRequestCallback != null && BadRequestCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for BadRequestCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.BadRequest)
			{
				BadRequestCallback?.Invoke(await response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false));
			}
			if(InternalServerErrorCallback != null && InternalServerErrorCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for InternalServerErrorCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
			{
				InternalServerErrorCallback?.Invoke();
			}
			if(ResponseCallback != null && ResponseCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for ResponseCallback are not supported. As they will run out of the scope of this call.");
			}
			ResponseCallback?.Invoke(response);
			return;
		}


		public async ValueTask<HttpResponseMessage> PutRawAsync(int id, 
			string value, 
			int UserId, 
			int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}/{id}?value={value}";
			HttpResponseMessage response = null;
			response = await HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false);
			if(response == null)
			{
				response = await Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("UserId", UserId)
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.PutJsonAsync(value,cancellationToken).ConfigureAwait(false);
				
				await HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false);
			}

			return response;
		}


		public void Delete(int id, 
			int UserId, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			SecurityHeader auth = null, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}/{id}";
			HttpResponseMessage response = null;
			response = HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			if(response == null)
			{
				response = Client.ClientWrapper
				.Request(url)
				.WithAuth(auth)
				.WithHeader("Accept", "application/json")
				.WithHeader("UserId", UserId)
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.DeleteAsync(cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
				
				HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			}

			if(BadRequestCallback != null && BadRequestCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for BadRequestCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.BadRequest)
			{
				BadRequestCallback?.Invoke(response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false).GetAwaiter().GetResult());
			}
			if(InternalServerErrorCallback != null && InternalServerErrorCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for InternalServerErrorCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
			{
				InternalServerErrorCallback?.Invoke();
			}
			if(ResponseCallback != null && ResponseCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for ResponseCallback are not supported. As they will run out of the scope of this call.");
			}
			ResponseCallback?.Invoke(response);
			return;
		}


		public HttpResponseMessage DeleteRaw(int id, 
			int UserId, 
			int ControllerHeader = 0, 
			SecurityHeader auth = null, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}/{id}";
			HttpResponseMessage response = null;
			response = HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			if(response == null)
			{
				response = Client.ClientWrapper
				.Request(url)
				.WithAuth(auth)
				.WithHeader("Accept", "application/json")
				.WithHeader("UserId", UserId)
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.DeleteAsync(cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
				
				HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			}

			return response;
		}


		public async Task DeleteAsync(int id, 
			int UserId, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			SecurityHeader auth = null, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}/{id}";
			HttpResponseMessage response = null;
			response = await HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false);
			if(response == null)
			{
				response = await Client.ClientWrapper
				.Request(url)
				.WithAuth(auth)
				.WithHeader("Accept", "application/json")
				.WithHeader("UserId", UserId)
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.DeleteAsync(cancellationToken).ConfigureAwait(false);
				
				await HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false);
			}

			if(BadRequestCallback != null && BadRequestCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for BadRequestCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.BadRequest)
			{
				BadRequestCallback?.Invoke(await response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false));
			}
			if(InternalServerErrorCallback != null && InternalServerErrorCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for InternalServerErrorCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
			{
				InternalServerErrorCallback?.Invoke();
			}
			if(ResponseCallback != null && ResponseCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for ResponseCallback are not supported. As they will run out of the scope of this call.");
			}
			ResponseCallback?.Invoke(response);
			return;
		}


		public async ValueTask<HttpResponseMessage> DeleteRawAsync(int id, 
			int UserId, 
			int ControllerHeader = 0, 
			SecurityHeader auth = null, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";


			string url = $@"api/{controller}/{id}";
			HttpResponseMessage response = null;
			response = await HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false);
			if(response == null)
			{
				response = await Client.ClientWrapper
				.Request(url)
				.WithAuth(auth)
				.WithHeader("Accept", "application/json")
				.WithHeader("UserId", UserId)
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.DeleteAsync(cancellationToken).ConfigureAwait(false);
				
				await HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false);
			}

			return response;
		}


		public void CancellationTestEndpoint(int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";
			var action = "CancellationTestEndpoint";

			string url = $@"api/{controller}/{action}";
			HttpResponseMessage response = null;
			response = HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			if(response == null)
			{
				response = Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.GetAsync(cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
				
				HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			}

			if(BadRequestCallback != null && BadRequestCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for BadRequestCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.BadRequest)
			{
				BadRequestCallback?.Invoke(response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false).GetAwaiter().GetResult());
			}
			if(InternalServerErrorCallback != null && InternalServerErrorCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for InternalServerErrorCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
			{
				InternalServerErrorCallback?.Invoke();
			}
			if(ResponseCallback != null && ResponseCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for ResponseCallback are not supported. As they will run out of the scope of this call.");
			}
			ResponseCallback?.Invoke(response);
			return;
		}


		public HttpResponseMessage CancellationTestEndpointRaw(int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";
			var action = "CancellationTestEndpoint";

			string url = $@"api/{controller}/{action}";
			HttpResponseMessage response = null;
			response = HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			if(response == null)
			{
				response = Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.GetAsync(cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
				
				HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			}

			return response;
		}


		public async Task CancellationTestEndpointAsync(int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";
			var action = "CancellationTestEndpoint";

			string url = $@"api/{controller}/{action}";
			HttpResponseMessage response = null;
			response = await HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false);
			if(response == null)
			{
				response = await Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.GetAsync(cancellationToken).ConfigureAwait(false);
				
				await HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false);
			}

			if(BadRequestCallback != null && BadRequestCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for BadRequestCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.BadRequest)
			{
				BadRequestCallback?.Invoke(await response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false));
			}
			if(InternalServerErrorCallback != null && InternalServerErrorCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for InternalServerErrorCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
			{
				InternalServerErrorCallback?.Invoke();
			}
			if(ResponseCallback != null && ResponseCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for ResponseCallback are not supported. As they will run out of the scope of this call.");
			}
			ResponseCallback?.Invoke(response);
			return;
		}


		public async ValueTask<HttpResponseMessage> CancellationTestEndpointRawAsync(int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";
			var action = "CancellationTestEndpoint";

			string url = $@"api/{controller}/{action}";
			HttpResponseMessage response = null;
			response = await HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false);
			if(response == null)
			{
				response = await Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.GetAsync(cancellationToken).ConfigureAwait(false);
				
				await HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false);
			}

			return response;
		}


		public string HeaderTest(String SpecialValue1, 
			string SpecialValue2, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";
			var action = "HeaderTest";

			string url = $@"api/{controller}/{action}";
			HttpResponseMessage response = null;
			response = HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			if(response == null)
			{
				response = Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("SpecialValue1", SpecialValue1)
				.WithHeader("SpecialValue2", SpecialValue2)
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.GetAsync(cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
				
				HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			}

			if(BadRequestCallback != null && BadRequestCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for BadRequestCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.BadRequest)
			{
				BadRequestCallback?.Invoke(response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false).GetAwaiter().GetResult());
			}
			if(InternalServerErrorCallback != null && InternalServerErrorCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for InternalServerErrorCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
			{
				InternalServerErrorCallback?.Invoke();
			}
			if(ResponseCallback != null && ResponseCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for ResponseCallback are not supported. As they will run out of the scope of this call.");
			}
			ResponseCallback?.Invoke(response);
			
			if(response.IsSuccessStatusCode)
			{
				return response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false).GetAwaiter().GetResult();
			}
			else
			{
				return null;
			}

		}


		public HttpResponseMessage HeaderTestRaw(String SpecialValue1, 
			string SpecialValue2, 
			int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";
			var action = "HeaderTest";

			string url = $@"api/{controller}/{action}";
			HttpResponseMessage response = null;
			response = HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			if(response == null)
			{
				response = Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("SpecialValue1", SpecialValue1)
				.WithHeader("SpecialValue2", SpecialValue2)
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.GetAsync(cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
				
				HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
			}

			return response;
		}


		public async ValueTask<string> HeaderTestAsync(String SpecialValue1, 
			string SpecialValue2, 
			int ControllerHeader = 0, 
			Action<string> BadRequestCallback = null, 
			Action InternalServerErrorCallback = null, 
			Action<HttpResponseMessage> ResponseCallback = null, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";
			var action = "HeaderTest";

			string url = $@"api/{controller}/{action}";
			HttpResponseMessage response = null;
			response = await HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false);
			if(response == null)
			{
				response = await Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("SpecialValue1", SpecialValue1)
				.WithHeader("SpecialValue2", SpecialValue2)
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.GetAsync(cancellationToken).ConfigureAwait(false);
				
				await HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false);
			}

			if(BadRequestCallback != null && BadRequestCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for BadRequestCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.BadRequest)
			{
				BadRequestCallback?.Invoke(await response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false));
			}
			if(InternalServerErrorCallback != null && InternalServerErrorCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for InternalServerErrorCallback are not supported. As they will run out of the scope of this call.");
			}
			if(response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
			{
				InternalServerErrorCallback?.Invoke();
			}
			if(ResponseCallback != null && ResponseCallback.Method.IsDefined(typeof(AsyncStateMachineAttribute), true))
			{
				throw new NotSupportedException("Async void action delegates for ResponseCallback are not supported. As they will run out of the scope of this call.");
			}
			ResponseCallback?.Invoke(response);
			
			if(response.IsSuccessStatusCode)
			{
				return await response.Content.ReadAsNonJsonAsync<string>().ConfigureAwait(false);
			}
			else
			{
				return null;
			}

		}


		public async ValueTask<HttpResponseMessage> HeaderTestRawAsync(String SpecialValue1, 
			string SpecialValue2, 
			int ControllerHeader = 0, 
			CancellationToken cancellationToken = default(CancellationToken))
		{

			
			var controller = "Values";
			var action = "HeaderTest";

			string url = $@"api/{controller}/{action}";
			HttpResponseMessage response = null;
			response = await HttpOverride.GetResponseAsync(url, cancellationToken).ConfigureAwait(false);
			if(response == null)
			{
				response = await Client.ClientWrapper
				.Request(url)
				.WithHeader("Accept", "application/json")
				.WithHeader("SpecialValue1", SpecialValue1)
				.WithHeader("SpecialValue2", SpecialValue2)
				.WithHeader("ControllerHeader", ControllerHeader)
				.AllowAnyHttpStatus()
				.GetAsync(cancellationToken).ConfigureAwait(false);
				
				await HttpOverride.OnNonOverridedResponseAsync(url, response, cancellationToken).ConfigureAwait(false);
			}

			return response;
		}

	}


}
